import { chat } from './llm'
import type { DraftCandidate } from './types'

/**
 * Agent tool registry. Each tool is a pure-ish function the runner calls
 * between LLM steps. Tools keep the agent grounded and avoid hallucinated state.
 */

export async function hashtagTool(text: string): Promise<string[]> {
  const res = await chat({
    system: 'Suggest 4-8 relevant, non-spammy hashtags for a social post. Return JSON {"hashtags":["..."]}.',
    user: text,
    json: true,
    temperature: 0.5,
  })
  if (!res) return []
  try {
    const parsed = JSON.parse(res.text || '{}')
    const tags = Array.isArray(parsed.hashtags) ? parsed.hashtags : []
    return tags.slice(0, 8).map((t: string) => String(t).replace(/^#/, ''))
  } catch {
    return []
  }
}

export async function scoreTool(content: string, tone?: string): Promise<{ score: number; notes: string }> {
  const res = await chat({
    system: `You are a strict social content reviewer for tone "${tone ?? 'professional'}".`,
    user: `Review:\n${content}\nReturn JSON {"score":0-100,"notes":"..."}.`,
    json: true,
    temperature: 0.2,
  })
  if (!res) return { score: 75, notes: 'Auto-passed (reviewer unavailable).' }
  try {
    const parsed = JSON.parse(res.text || '{}')
    return { score: Math.max(0, Math.min(100, Number(parsed.score) || 70)), notes: String(parsed.notes ?? '') }
  } catch {
    return { score: 70, notes: 'Could not parse review.' }
  }
}

/**
 * Deterministic fallback generator used when no LLM is configured, so the
 * platform remains functional in local/dev without an OpenAI key.
 */
export function fallbackGenerate(goal: string, topics: string[]): DraftCandidate[] {
  const topic = topics[0] ?? 'your niche'
  const content = `🚀 ${goal}\n\nHere's a quick win on ${topic}: start small, stay consistent, and measure what resonates. #${topic.replace(/\s+/g, '')}`
  return [
    {
      content,
      platforms: ['X'],
      topic,
      hashtags: [topic.replace(/\s+/g, '')],
      notes: 'Generated by offline fallback (no LLM configured).',
      agentScore: 60,
    },
  ]
}
